spring.application.name=chatservice

server.port=9091

spring.datasource.url=jdbc:postgresql://localhost:5432/MithrilChatApp-ChatDB
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/mithrilApi-chat-docs