spring.application.name=chatservice

server.port=9091

spring.datasource.url=jdbc:postgresql://localhost:5432/MithrilChatApp-ChatDB
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OpenAPI 3.0 documentation (Swagger)
springdoc.api-docs.path=/mithrilApi-chat-docs

# Redis configuration
spring.redis.host=localhost
spring.redis.port=6379

# application instance id
spring.application.instance-id=${random.uuid}